phrase_options = [
'Never give up hope',
'Dream big work hard',
'Love what you do',
'Believe in yourself',
'Dream plan execute',
'Think big act bigger',
'Create your own destiny',
'Strive for greatness',
'Live with intention',
'Stay focused never give up',
'Work hard be kind',
'Dream big start small',
'Stay positive be happy',
'Strive for excellence',
'Live with determination',
'Stay strong stay inspired',
'Dream focus achieve',
'Create your own path',
'Work hard stay focused',
'Dream big never stop',
'Stay the course',
'Create your own sunshine',
'Be the change',
'Believe in miracles',
'Stay committed never settle',
'Dream achieve inspire',
'Live with purpose',
'Stay positive stay motivated',
'Believe in your journey',
'Work hard be fearless',
'Believe in your dreams',
'Dream believe achieve',
'Strive for success',
'Stay committed stay motivated',
'Dream big stay focused',
'Stay positive stay hopeful',
'Believe in yourself always',
'Work hard stay humble',
'Dream big stay positive',
'Stay positive be kind',
'Strive for greatness always',
'Live with purpose always',
'Stay committed never give-up',
'Believe in your potential',
'Dream achieve inspire succeed',
'Live with intention always',
'Dream big never give up',
'Strive for excellence always',
'Live with determination always',
'Dream focus achieve succeed',
'Dream plan execute repeat',
'Dream believe achieve succeed',
'Strive for success always',
'Dream focus achieve inspire',
'Live with purpose daily',
'Believe in yourself forever',
'Strive for greatness forever',
'Live with intention daily',
'Live with determination daily',
'Strive for success daily',
'Strive for greatness daily',
'Live with intention forever',
'Live your dream now',
'Success is a journey',
'Turn your wounds into wisdom',
'Chase your wildest dreams',
'Think believe achieve succeed',
'Believe you can achieve',
'Stay positive stay fighting',
'Work hard stay committed',
'Dream plan execute achieve',
'Live with passion always',
'Dream focus achieve repeat',
'Believe achieve inspire repeat',
'Never stop believing in yourself',
'Believe achieve inspire succeed',
'Dream focus achieve persist',
'Strive for excellence daily',
'Create your own magic',
'Stay the course always',
'Believe in your strength',
'Never ever stop believing',
'Be the change today',
'Live laugh love repeat',
'Nothing is impossible here',
'You can do it',
'Happiness is a choice',
'Every moment is precious',
'Learn from your mistakes',
'Success is not final',
'Failure is not fatal',
'The journey is everything',
'Quality over quantity always',
'Less is more sometimes',
'Do what you love',
'Keep calm and carry on',
'Make every day count',
'The best is yet to come',
'You are not alone',
'You are enough today',
'You are a masterpiece',
'You are a miracle',
'You have a purpose',
'You have unlimited potential',
'Follow your heart always',
'Trust your intuition sometimes',
'Listen to your inner voice',
'Challenge yourself every day',
'Embrace the unknown future',
'Enjoy the present moment',
'Appreciate the past lessons',
'Forgive yourself and others',
'Be kind to everyone',
'Be grateful for everything',
'Be humble and generous',
'Be honest and courageous',
'Be optimistic and realistic',
'Be creative and curious'
]